//! LLM-driven triage prompt + JSON schema.
//!
//! Asks the cheap-tier model to classify each file into one of
//! {trivial, formatting, doc, simple, complex}. The pipeline can then
//! drop trivial/formatting/doc files from the heavy reasoning prompt to
//! save tokens — same idea as CodeRabbit's two-tier routing.
//!
//! The full classifier is currently only the prompt + schema + types;
//! orchestration (call cheap-tier, filter, fall back when cheap-tier
//! isn't configured) is a follow-up.

use serde::{Deserialize, Serialize};
use std::sync::OnceLock;

const TRIAGE_SCHEMA_JSON: &str = include_str!("../schemas/triage.json");

static TRIAGE_SCHEMA: OnceLock<serde_json::Value> = OnceLock::new();

pub fn triage_schema() -> &'static serde_json::Value {
    TRIAGE_SCHEMA.get_or_init(|| {
        serde_json::from_str(TRIAGE_SCHEMA_JSON)
            .expect("triage schema is valid JSON at compile-time")
    })
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TriageClass {
    /// Autogenerated, vendored, lockfile — skip review entirely.
    Trivial,
    /// Whitespace / style-only — skip the heavy review.
    Formatting,
    /// Docs / comments only — skip the heavy review.
    Doc,
    /// Small targeted change. Reviewable but a light pass is fine.
    Simple,
    /// Needs deep review.
    Complex,
}

impl TriageClass {
    /// True iff this class merits running the reasoning-tier review.
    pub fn merits_full_review(self) -> bool {
        matches!(self, TriageClass::Simple | TriageClass::Complex)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct TriageEntry {
    pub path: String,
    pub class: TriageClass,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct TriageOutput {
    pub classifications: Vec<TriageEntry>,
}

const TRIAGE_SYSTEM_PROMPT: &str = "\
You are a fast, cheap classifier for code-review triage. For each file in \
the diff you are shown, output a class indicating how much review attention \
it needs.

Classes:
- trivial: autogenerated, vendored, lockfile, build artifact.
- formatting: whitespace, line-ending, or style-only changes.
- doc: documentation or comment changes only.
- simple: small targeted change, low risk.
- complex: substantive change that needs deep review.

Output ONLY a JSON object matching the provided schema. No prose, no \
markdown fences.";

pub fn triage_system_prompt() -> &'static str {
    TRIAGE_SYSTEM_PROMPT
}

#[derive(Debug, thiserror::Error)]
pub enum TriageValidationError {
    #[error("output is not valid JSON: {0}")]
    NotJson(String),
    #[error("output does not match schema: {0}")]
    SchemaMismatch(String),
}

pub fn validate_triage_output(json: &str) -> Result<TriageOutput, TriageValidationError> {
    let value: serde_json::Value =
        serde_json::from_str(json).map_err(|e| TriageValidationError::NotJson(e.to_string()))?;
    serde_json::from_value::<TriageOutput>(value)
        .map_err(|e| TriageValidationError::SchemaMismatch(e.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn schema_is_titled_triage_with_classifications_required() {
        let s = triage_schema();
        assert_eq!(s["title"], "Triage");
        let req = s["required"]
            .as_array()
            .unwrap()
            .iter()
            .filter_map(|v| v.as_str())
            .collect::<Vec<_>>();
        assert_eq!(req, vec!["classifications"]);
    }

    #[test]
    fn schema_constrains_class_to_five_levels() {
        let s = triage_schema();
        let levels: Vec<&str> = s["properties"]["classifications"]["items"]["properties"]["class"]
            ["enum"]
            .as_array()
            .unwrap()
            .iter()
            .filter_map(|v| v.as_str())
            .collect();
        assert_eq!(
            levels,
            vec!["trivial", "formatting", "doc", "simple", "complex"]
        );
    }

    #[test]
    fn merits_full_review_is_simple_or_complex() {
        assert!(!TriageClass::Trivial.merits_full_review());
        assert!(!TriageClass::Formatting.merits_full_review());
        assert!(!TriageClass::Doc.merits_full_review());
        assert!(TriageClass::Simple.merits_full_review());
        assert!(TriageClass::Complex.merits_full_review());
    }

    #[test]
    fn validate_accepts_well_formed_output() {
        let json = r#"{
            "classifications": [
                {"path":"src/a.rs","class":"complex"},
                {"path":"docs/readme.md","class":"doc"}
            ]
        }"#;
        let out = validate_triage_output(json).expect("ok");
        assert_eq!(out.classifications.len(), 2);
        assert_eq!(out.classifications[0].class, TriageClass::Complex);
        assert_eq!(out.classifications[1].class, TriageClass::Doc);
    }

    #[test]
    fn validate_rejects_non_json() {
        let err = validate_triage_output("not json").expect_err("err");
        assert!(matches!(err, TriageValidationError::NotJson(_)));
    }

    #[test]
    fn validate_rejects_unknown_class() {
        let json = r#"{"classifications":[{"path":"a","class":"weird"}]}"#;
        let err = validate_triage_output(json).expect_err("err");
        assert!(matches!(err, TriageValidationError::SchemaMismatch(_)));
    }

    #[test]
    fn validate_rejects_missing_classifications_field() {
        let err = validate_triage_output("{}").expect_err("err");
        assert!(matches!(err, TriageValidationError::SchemaMismatch(_)));
    }

    #[test]
    fn validate_rejects_unknown_top_level_field() {
        let json = r#"{"classifications":[],"extra":1}"#;
        let err = validate_triage_output(json).expect_err("err");
        assert!(matches!(err, TriageValidationError::SchemaMismatch(_)));
    }

    #[test]
    fn triage_system_prompt_mentions_each_class() {
        let p = triage_system_prompt();
        for c in ["trivial", "formatting", "doc", "simple", "complex"] {
            assert!(p.contains(c), "prompt missing class label: {c}");
        }
    }
}
