//! Pre-review triage. Classifies each changed file by likely review value
//! using path/extension heuristics — no LLM call, deterministic, free.
//!
//! The point is to skip *whole-PR* review when every file is "trivial" (e.g.
//! lockfile bumps, vendored output, autogenerated assets). Mixed PRs still
//! get the full pipeline — partial filtering of the diff inside an
//! otherwise-meaningful PR isn't worth the complexity yet.
//!
//! LLM-driven triage (CodeRabbit's cheap-model classifier) is a Milestone 2
//! follow-up; the seam is here.

use ar_forgejo::ChangedFile;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FileClass {
    /// Auto-generated, vendored, or otherwise not worth a review pass.
    Trivial,
    /// Anything else.
    Reviewable,
}

/// Classify a single changed file purely by name.
pub fn classify(filename: &str) -> FileClass {
    let lower = filename.to_ascii_lowercase();
    let basename = lower.rsplit('/').next().unwrap_or(&lower);

    if is_lockfile(basename) || is_generated_path(&lower) || is_vendored(&lower) {
        FileClass::Trivial
    } else {
        FileClass::Reviewable
    }
}

/// True iff every file in `files` is [`FileClass::Trivial`] — meaning the
/// entire PR can be skipped. An empty list is *not* skippable: that's a
/// data error, and we'd rather post an empty review than silently drop it.
///
/// Pure-removal PRs (every file has status="removed") are *not*
/// skippable either. Deletions are reviewable — a PR removing
/// security checks, tests, or load-bearing code deserves the same
/// scrutiny as a PR adding them. The previous filter+all idiom
/// would have returned true vacuously here (empty filtered set ⇒
/// `all` is true), silently skipping every pure-removal PR.
pub fn pr_is_skippable(files: &[ChangedFile]) -> bool {
    if files.is_empty() {
        return false;
    }
    let surviving: Vec<&ChangedFile> = files.iter().filter(|f| f.status != "removed").collect();
    if surviving.is_empty() {
        // Pure-removal PR: don't skip. Reviewing the deletion is
        // the operator's whole point.
        return false;
    }
    surviving
        .iter()
        .all(|f| classify(&f.filename) == FileClass::Trivial)
}

fn is_lockfile(basename: &str) -> bool {
    matches!(
        basename,
        "cargo.lock"
            | "package-lock.json"
            | "yarn.lock"
            | "pnpm-lock.yaml"
            | "poetry.lock"
            | "uv.lock"
            | "gemfile.lock"
            | "go.sum"
            | "composer.lock"
            | "mix.lock"
            | "bun.lockb"
            | "podfile.lock"
            | "flake.lock"
    )
}

fn is_generated_path(lower: &str) -> bool {
    lower.contains("/generated/")
        || lower.starts_with("generated/")
        || lower.contains(".pb.go")
        || lower.contains(".pb.rs")
        || lower.ends_with(".min.js")
        || lower.ends_with(".min.css")
        || lower.ends_with(".map")
}

fn is_vendored(lower: &str) -> bool {
    lower.contains("/vendor/")
        || lower.starts_with("vendor/")
        || lower.contains("/node_modules/")
        || lower.starts_with("node_modules/")
        || lower.contains("/third_party/")
        || lower.starts_with("third_party/")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cf(name: &str, status: &str) -> ChangedFile {
        ChangedFile {
            filename: name.into(),
            status: status.into(),
            additions: 0,
            deletions: 0,
            changes: 0,
            patch: None,
        }
    }

    #[test]
    fn ordinary_source_is_reviewable() {
        for name in [
            "src/main.rs",
            "src/lib/foo.ts",
            "scripts/build.sh",
            "Dockerfile",
            "README.md",
        ] {
            assert_eq!(classify(name), FileClass::Reviewable, "name = {name}");
        }
    }

    #[test]
    fn lockfiles_are_trivial() {
        for name in [
            "Cargo.lock",
            "package-lock.json",
            "yarn.lock",
            "pnpm-lock.yaml",
            "poetry.lock",
            "uv.lock",
            "Gemfile.lock",
            "go.sum",
            "frontend/package-lock.json",
            "flake.lock",
        ] {
            assert_eq!(classify(name), FileClass::Trivial, "name = {name}");
        }
    }

    #[test]
    fn generated_files_are_trivial() {
        for name in [
            "generated/api.go",
            "src/generated/proto.rs",
            "proto/foo.pb.go",
            "dist/app.min.js",
            "dist/app.min.css",
            "dist/app.js.map",
        ] {
            assert_eq!(classify(name), FileClass::Trivial, "name = {name}");
        }
    }

    #[test]
    fn vendored_files_are_trivial() {
        for name in [
            "vendor/github.com/x/y.go",
            "node_modules/foo/bar.js",
            "third_party/lib/x.c",
            "src/third_party/x.c",
        ] {
            assert_eq!(classify(name), FileClass::Trivial, "name = {name}");
        }
    }

    #[test]
    fn pr_with_only_lockfile_changes_is_skippable() {
        let files = vec![cf("Cargo.lock", "modified"), cf("yarn.lock", "modified")];
        assert!(pr_is_skippable(&files));
    }

    #[test]
    fn pr_with_any_reviewable_file_is_not_skippable() {
        let files = vec![cf("Cargo.lock", "modified"), cf("src/main.rs", "modified")];
        assert!(!pr_is_skippable(&files));
    }

    #[test]
    fn empty_pr_is_not_skippable() {
        assert!(!pr_is_skippable(&[]));
    }

    #[test]
    fn removed_files_dont_count_against_skippability() {
        // A PR that only removes vendored code should still be reviewable —
        // someone might want feedback on the deletion choice. But here we
        // verify that 'removed' status is filtered before the all-trivial
        // check so a mixed PR isn't accidentally flipped.
        let files = vec![
            cf("vendor/old.go", "removed"),
            cf("src/main.rs", "modified"),
        ];
        assert!(!pr_is_skippable(&files));
    }

    #[test]
    fn pure_removal_pr_is_not_skippable() {
        // A PR that ONLY deletes files — including trivial ones —
        // is reviewable. Removing tests, security checks, or
        // load-bearing code deserves the same scrutiny as adding
        // them. Without this rule, the previous filter+all idiom
        // returned true vacuously (empty filtered set ⇒ `all`
        // is true) and silently skipped the review.
        let files = vec![
            cf("Cargo.lock", "removed"),
            cf("yarn.lock", "removed"),
            cf("vendor/old.go", "removed"),
        ];
        assert!(
            !pr_is_skippable(&files),
            "pure-removal PR must still trigger review"
        );
    }
}
